jobs:
  build-and-test:
    uses: centic9/actions/.github/workflows/maven-build.yml@7
    with:
      fullCheckout: true
name: Build and check
on:
  repository_dispatch:
    types: trigger-ga___maven-build.yml
